### ISSUE TITLE
Masterwork metatags cause unreliable behavior with fetching raws

### ISSUE THREAD

**Issue by lethosor** [asvae/DFRawFunctions#10]
Using {{raw}} (essentially {{#df_raw}} with not_found filled in) to fetch raws fetches just the relevant raws with DF2012, but the _entire file_ with Masterwork raws:

```
<noinclude>{{raw header|plant|BLACK_CAP}}</noinclude>{{raw|DF2012:plant_standard.txt|PLANT|BLACK_CAP}}<noinclude>{{raw footer|plant|BLACK_CAP}}</noinclude>
```

![screen shot 2013-09-18 at 4 12 00 pm](https://f.cloud.github.com/assets/3719547/1168351/a429ebd4-209e-11e3-963b-9d433a64da33.png)

```
<noinclude>{{raw header|plant|BLACK_CAP}}</noinclude>{{raw|Masterwork:plant_standard.txt|PLANT|BLACK_CAP}}<noinclude>{{raw footer|plant|BLACK_CAP}}</noinclude>
```

![screen shot 2013-09-18 at 4 12 13 pm](https://f.cloud.github.com/assets/3719547/1168350/a41dc5ca-209e-11e3-94e4-bf4576db7b5f.png)

**Comment by asvae** [comment]
That is weird. Taken from Masterwork/plant_standard.txt:
1) !NOTREEPLANT:!PLANT:BLACK_CAP]
2) !NOTREEPLANT:!BLOOD_THORN]

I'll ask Meph to fix that.

**Comment by asvae** [comment]
Probably will be fixed for next release. [forum link](http://www.bay12forums.com/smf/index.php?topic=131011.msg4626502#msg4626502)

**Comment by lethosor** [comment]
Ah. That would explain the problems my earlier script was having with that file. Thanks!

**Comment by asvae** [comment]
Fixed with MDF v4.
